### ISSUE TITLE
Make hangout chat handling more robust

### ISSUE THREAD

**Issue by ppxl** [cloudogu/redmine-google-chat#7]
There will be a nasty `HTTP 500` from the plugin when given a project that has `Setting.plugin_redmine_hangouts_chat['hangouts_chat_url'] = '-'` when a ticket's parent ticket should be set or replace.

```
[e124d8db-d555-452a-af63-7608c1bdd536] Completed 500 Internal Server Error in 557ms (ActiveRecord: 310.6ms | Allocations: 74739)
[e124d8db-d555-452a-af63-7608c1bdd536]   
[e124d8db-d555-452a-af63-7608c1bdd536] TypeError (no implicit conversion of Issue into String):
[e124d8db-d555-452a-af63-7608c1bdd536]   
[e124d8db-d555-452a-af63-7608c1bdd536] plugins/redmine_hangouts_chat/lib/hangouts_chat/listener.rb:281:in `escapeHTML'
[e124d8db-d555-452a-af63-7608c1bdd536] plugins/redmine_hangouts_chat/lib/hangouts_chat/listener.rb:281:in `escape'
[e124d8db-d555-452a-af63-7608c1bdd536] plugins/redmine_hangouts_chat/lib/hangouts_chat/listener.rb:379:in `detail_to_field'
[e124d8db-d555-452a-af63-7608c1bdd536] plugins/redmine_hangouts_chat/lib/hangouts_chat/listener.rb:107:in `block in redmine_hangouts_chat_issues_edit_after_save'
[e124d8db-d555-452a-af63-7608c1bdd536] plugins/redmine_hangouts_chat/lib/hangouts_chat/listener.rb:107:in `map'
[e124d8db-d555-452a-af63-7608c1bdd536] plugins/redmine_hangouts_chat/lib/hangouts_chat/listener.rb:107:in `redmine_hangouts_chat_issues_edit_after_save'
[e124d8db-d555-452a-af63-7608c1bdd536] lib/redmine/hook.rb:66:in `block (2 levels) in call_hook'
[e124d8db-d555-452a-af63-7608c1bdd536] lib/redmine/hook.rb:66:in `each'
[e124d8db-d555-452a-af63-7608c1bdd536] lib/redmine/hook.rb:66:in `block in call_hook'
[e124d8db-d555-452a-af63-7608c1bdd536] lib/redmine/hook.rb:63:in `call_hook'
[e124d8db-d555-452a-af63-7608c1bdd536] plugins/redmine_hangouts_chat/lib/hangouts_chat/issue_patch.rb:26:in `save_from_issue'
[e124d8db-d555-452a-af63-7608c1bdd536] app/models/issue.rb:232:in `create_or_update'
[e124d8db-d555-452a-af63-7608c1bdd536] app/controllers/issues_controller.rb:669:in `block in save_issue_with_child_records'
[e124d8db-d555-452a-af63-7608c1bdd536] app/controllers/issues_controller.rb:650:in `save_issue_with_child_records'
[e124d8db-d555-452a-af63-7608c1bdd536] app/controllers/issues_controller.rb:205:in `update'
```

The exact conditions to reproduce this behaviour is not easily possible but the following things could be observed:

1. this Plugin must be installed
2. the project is configured to have `-` both as value for the _hangouts chat URL_ as well as  _hangouts chat thread_
3. the ticket to be modified is of type `Idea`, or `User story` (this most likely plays no role)
4. the parent-to-be is of type `Epic`
5. the ticket to be modified is not new and must be modified

**Comment by ppxl** [comment]
The change works, both with tickets whose project configures a Google Chat URL and for those without. For those with configured Chat URLs the testworkflow works as follows:

1. Open a ticket whose project configures a Google Chat URL, f. i. a Support project
2. Change the field `Priority` and add a short comment
3. Save the ticket

This should positively lead to a notice in Google Chat. In the Redmine logs an Info notice like this:
`found google chat ticket to url https://chat.googleapis.com/v1/spaces/ASPACEgoesHere/messages?key=aKeyGoesHere&token=aTokenGoesHere`

Since the log contains a trace UUID, the respective ticket ID can be fetched from a previously printed log line with the same trace UUID which shows all ticket's fields.

**Comment by ppxl** [comment]
Fix did not work. Fix must be re-created.
